---
title: "Main"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Dependencies
```{r}
library(tidyverse)
library(plotly)
library(dplyr)
library(klaR)
library(ggpubr)
```

```{r}
data.tb <- read_csv("./data/BlackFriday.csv")
#data.tb %>% head(25)

data_random.tb <- sample_n(data.tb, 2000, replace=TRUE)

#data_random_unique.tb <- unique(data_random.tb)

#test.tb <- data.tb %>% head(2000)

```
#find unique values for Age
```{r}
unique(data_random.tb$Age)  
```

#functions to filter Ages into return values (numeric representations of the group)
```{r}
ageFilter <- function(age) {
  switch(age, "0-17"=1, "18-25"=2, "26-35"=3, "36-45"=4, "46-50"=5, "51-55"=6, "55+"=7)
}
ageFilter("51-55")
```
#pipe Age vector into ageFilter(), append to tibble
```{r}
##data.tb$age <- ageFilter(data.tb$Age)
data_random.tb$age <- data_random.tb$Age

#data.tb %>% head()
for (i in 1:length(data_random.tb$age)) {
  data_random.tb$age[i] <- ageFilter(data_random.tb$age[i])
  ##print(test.tb$Age + " " + test.tb$age)
}

#make numeric
data_random.tb$age <- data_random.tb$age %>% as.numeric()
```

#Regression: Age vs Purchase Value
```{r}
fit <- lm(formula= data_random.tb$Purchase ~ data_random.tb$age + 0, data=data_random.tb)
fit[1]
```
#Correlation: Age vs Purchase Value
```{r}
cor(data_random.tb$age %>% as.numeric(), data_random.tb$Purchase %>% as.numeric())
```

```{r}
anova <- aov(data_random.tb$Purchase ~ data_random.tb$Age, data = data_random.tb)
summary(anova)
```

```{r}
data_random_na.tb <- na.omit(data_random.tb)

plot <- plot_ly(
  x = c(data_random_na.tb$Age),
  y = c(data_random_na.tb$Purchase),
  name = "Age vs. Purchase Amount",
  type = "bar"
)

plot
```

```{r}
ggboxplot(data_random_na.tb, x = "Age", y = "Purchase", 
          order = c("0-17", "18-25", "26-35", "36-45", "46-50", "51-55", "55+" ),
          ylab = "Money Spent", xlab = "Age")
```



